// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Token struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	TokenType  string     `json:"token_type"`
	Jti        string     `json:"jti"`
	ExpiresAt  time.Time  `json:"expires_at"`
	Revoked    bool       `json:"revoked"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID  `json:"id"`
	Sub         string     `json:"sub"`
	Provider    string     `json:"provider"`
	Email       string     `json:"email"`
	DisplayName *string    `json:"display_name"`
	Role        string     `json:"role"`
	Scopes      []string   `json:"scopes"`
	Groups      []string   `json:"groups"`
	LastLoginAt *time.Time `json:"last_login_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}
