// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (user_id, name, scopes, token_type, jti, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, scopes, token_type, jti, expires_at, revoked, last_used_at, created_at, updated_at
`

type CreateTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Scopes    []string  `json:"scopes"`
	TokenType string    `json:"token_type"`
	Jti       string    `json:"jti"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Name,
		arg.Scopes,
		arg.TokenType,
		arg.Jti,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scopes,
		&i.TokenType,
		&i.Jti,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, user_id, name, scopes, token_type, jti, expires_at, revoked, last_used_at, created_at, updated_at
FROM tokens
WHERE id = $1
  AND user_id = $2
`

type GetTokenByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTokenByID(ctx context.Context, arg GetTokenByIDParams) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByID, arg.ID, arg.UserID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scopes,
		&i.TokenType,
		&i.Jti,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByJTI = `-- name: GetTokenByJTI :one
SELECT id, user_id, name, scopes, token_type, jti, expires_at, revoked, last_used_at, created_at, updated_at
FROM tokens
WHERE jti = $1
`

func (q *Queries) GetTokenByJTI(ctx context.Context, jti string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByJTI, jti)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scopes,
		&i.TokenType,
		&i.Jti,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, name, scopes, token_type, jti, expires_at, revoked, last_used_at, created_at, updated_at
FROM tokens
WHERE user_id = $1
  AND revoked IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID uuid.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Scopes,
			&i.TokenType,
			&i.Jti,
			&i.ExpiresAt,
			&i.Revoked,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE tokens
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTokenUsed, id)
	return err
}

const revokeToken = `-- name: RevokeToken :one
UPDATE tokens
SET revoked = TRUE,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, scopes, token_type, jti, expires_at, revoked, last_used_at, created_at, updated_at
`

type RevokeTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, revokeToken, arg.ID, arg.UserID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scopes,
		&i.TokenType,
		&i.Jti,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
