// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, sub, provider, email, display_name, role, scopes, groups, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Provider,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Scopes,
		&i.Groups,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderSub = `-- name: GetUserByProviderSub :one
SELECT id, sub, provider, email, display_name, role, scopes, groups, last_login_at, created_at, updated_at FROM users WHERE provider = $1 AND sub = $2
`

type GetUserByProviderSubParams struct {
	Provider string `json:"provider"`
	Sub      string `json:"sub"`
}

func (q *Queries) GetUserByProviderSub(ctx context.Context, arg GetUserByProviderSubParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderSub, arg.Provider, arg.Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Provider,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Scopes,
		&i.Groups,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, sub, provider, email, display_name, role, scopes, groups, last_login_at, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Sub,
			&i.Provider,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Scopes,
			&i.Groups,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (sub, provider, email, display_name, role, scopes, groups, last_login_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
ON CONFLICT (provider, sub)
DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    role = EXCLUDED.role,
    scopes = EXCLUDED.scopes,
    groups = EXCLUDED.groups,
    last_login_at = EXCLUDED.last_login_at,
    updated_at = now()
RETURNING id, sub, provider, email, display_name, role, scopes, groups, last_login_at, created_at, updated_at
`

type UpsertUserParams struct {
	Sub         string     `json:"sub"`
	Provider    string     `json:"provider"`
	Email       string     `json:"email"`
	DisplayName *string    `json:"display_name"`
	Role        string     `json:"role"`
	Scopes      []string   `json:"scopes"`
	Groups      []string   `json:"groups"`
	LastLoginAt *time.Time `json:"last_login_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Sub,
		arg.Provider,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.Scopes,
		arg.Groups,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Provider,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Scopes,
		&i.Groups,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
