name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GOPATH: /go_path
  GOCACHE: /go_cache

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 5m

      - name: Check code formatting
        run: golangci-lint fmt --diff

      - name: Static analysis
        run: go vet ./...

      - name: Run tests
        run: go tool gotestsum --junitfile results/unit-tests.xml

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile
        working-directory: ui

      - name: Lint with eslint
        shell: bash
        run: bun run lint
        working-directory: ui

      - name: Run npm audit
        shell: bash
        run: bun audit
        working-directory: ui

  build-images:
    name: Build image
    runs-on: ubuntu-latest
    needs:
      - test
      - eslint

    strategy:
      matrix:
        app: [server, worker, scheduler, ui]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: ./docker/${{ matrix.app }}/Dockerfile
          build-args: ${{ matrix.app == 'ui' && 'NEXT_TELEMETRY_DISABLED=1' || '' }}
